heat_template_version: 2015-04-30
resources:
  loadbalancer:
    type: OS::Octavia::LoadBalancer
    properties:
      admin_state_up: True
      name: load_balancer
      vip_subnet: 3c52eccd-1ce1-48ae-baa0-51e4cfb39f85

  listner:
    type: OS::Octavia::Listener
    properties:
      admin_state_up: True
      connection_limit: -1
      loadbalancer: { get_resource: loadbalancer }
      name: listner
      protocol: HTTP
      protocol_port: 80
  
  pool:
    type: OS::Octavia::Pool
    properties:
      admin_state_up: True
      lb_algorithm: ROUND_ROBIN
      listener: { get_resource: listner }
      loadbalancer: { get_resource: loadbalancer }
      name: pool
      protocol: HTTP

  pool_member:
    type: OS::Octavia::PoolMember
    properties:
      address: 192.168.65.54
      admin_state_up: True
      pool: { get_resource: pool }
      protocol_port: 80
      subnet: 3c52eccd-1ce1-48ae-baa0-51e4cfb39f85
      weight: 1

  pool_member:
    type: OS::Octavia::PoolMember
    properties:
      address: 192.168.65.55
      admin_state_up: True
      pool: { get_resource: pool }
      protocol_port: 80
      subnet: 3c52eccd-1ce1-48ae-baa0-51e4cfb39f85
      weight: 1

  pool_member:
    type: OS::Octavia::PoolMember
    properties:
      address: 192.168.65.56
      admin_state_up: True
      pool: { get_resource: pool }
      protocol_port: 80
      subnet: 3c52eccd-1ce1-48ae-baa0-51e4cfb39f85
      weight: 1

  healthmonitor:
    type: OS::Octavia::HealthMonitor
    properties:
      admin_state_up: True
      delay: 5
      max_retries: 3
      pool: { get_resource: pool}
      timeout: 5
      type: PING
 
