heat_template_version: 2015-04-30
resources:
  server:
    type: OS::Nova::Server
    properties:
      admin_pass: 1234
      flavor: app_flavor
      image: ubuntu20.04
      key_name: test
      name: testServer
      networks: [{"network": public}]
